spring:
  datasource:
    url: jdbc:mysql://localhost:13306/everytime_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USERNAME:team3}
    password: ${DB_PASSWORD:everytime_pw}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8080

jwt:
  secret: aaaa-secret-key-aaaa-bb-cc-ddddd-256-bits-long-for-HS256-algorithm-everytime-clone-project-team3
  expiration: 86400000