services:
  app:
    image: leeym1/everytime:latest
    container_name: everytime-app
    env_file:
      - .env.prod     # 실제 서버에서 제공
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_JSON={
        "jwt":{"secret":" aaaa-secret-key-aaaa-bb-cc-ddddd-256-bits-long-for-HS256-algorithm-everytime-clone-project-team3","expiration":86400000},
        "spring":{"datasource":{
        "url":"jdbc:mysql://everytime-mysql:13306/everytime_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=UTC",
        "username":"team3",
        "password":"everytime_pw"
        }}
        }
    ports:
      - "80:8080"
    depends_on:
      everytime-mysql:
        condition: service_healthy
    restart: unless-stopped

  everytime-mysql:
    image: mysql:8.0.43
    container_name: everytime-mysql
    env_file:
      - .env.prod
    command: [
      "--default-authentication-plugin=caching_sha2_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - ./_vol/mysql:/var/lib/mysql
    restart: unless-stopped